import reflex as rx

import index.constants as constants
import index.styles.styles as styles


def services() -> rx.Component:
    return rx.hstack(
        rx.vstack(
            rx.vstack(
                rx.heading(
                    constants.SERVICES_TITLE,
                    size="lg",
                    color="white",
                    style=styles.h2_section_title_text_style,
                ),
                rx.text(
                    constants.SERVICES_CONTENT,
                    style=[
                        styles.parragraph_text_style,
                        styles.service_parragraph_style,
                    ],
                ),
                style=styles.section_title_style,
            ),
            rx.flex(
                rx.flex(
                    rx.vstack(
                        rx.vstack(
                            rx.icon(
                                tag="plus_square",
                                style=styles.sevice_icon_style,
                            ),
                            style=styles.service_icon_container_style,
                        ),
                        rx.heading(
                            rx.link(
                                constants.SERVICE_1_NAME,
                                href="#",
                                style=styles.link_style,
                            ),
                            as_="h4",
                            style=styles.h4_style,
                        ),
                        rx.text(
                            constants.SERVICE_1_DESCRIPTION,
                            style=[
                                styles.parragraph_text_style,
                                styles.service_parragraph_style,
                            ],
                        ),
                        style=styles.services_icon_box_style,
                    ),
                    style=[
                        styles.services_col_style,
                        styles.d_flex_style,
                        styles.align_items_stretch_style,
                    ],
                ),
                rx.flex(
                    rx.vstack(
                        rx.vstack(
                            rx.icon(
                                tag="plus_square",
                                style=styles.sevice_icon_style,
                            ),
                            style=styles.service_icon_container_style,
                        ),
                        rx.heading(
                            rx.link(
                                constants.SERVICE_2_NAME,
                                href="#",
                                style=styles.link_style,
                            ),
                            as_="h4",
                            style=styles.h4_style,
                        ),
                        rx.text(
                            constants.SERVICE_2_DESCRIPTION,
                            style=[
                                styles.parragraph_text_style,
                                styles.service_parragraph_style,
                            ],
                        ),
                        style=styles.services_icon_box_style,
                    ),
                    style=[
                        styles.services_col_style,
                        styles.d_flex_style,
                        styles.align_items_stretch_style,
                        styles.mt_4_style,
                        styles.mt_md_0_style,
                    ],
                ),
                rx.flex(
                    rx.vstack(
                        rx.vstack(
                            rx.icon(
                                tag="plus_square",
                                style=styles.sevice_icon_style,
                            ),
                            style=styles.service_icon_container_style,
                        ),
                        rx.heading(
                            rx.link(
                                constants.SERVICE_3_NAME,
                                href="#",
                                style=styles.link_style,
                            ),
                            as_="h4",
                            style=styles.h4_style,
                        ),
                        rx.text(
                            constants.SERVICE_3_DESCRIPTION,
                            style=[
                                styles.parragraph_text_style,
                                styles.service_parragraph_style,
                            ],
                        ),
                        style=styles.services_icon_box_style,
                    ),
                    style=[
                        styles.services_col_style,
                        styles.d_flex_style,
                        styles.align_items_stretch_style,
                        styles.mt_4_style,
                        styles.mt_xl_0_style,
                    ],
                ),
                rx.flex(
                    rx.vstack(
                        rx.vstack(
                            rx.icon(
                                tag="plus_square",
                                style=styles.sevice_icon_style,
                            ),
                            style=styles.service_icon_container_style,
                        ),
                        rx.heading(
                            rx.link(
                                constants.SERVICE_4_NAME,
                                href="#",
                                style=styles.link_style,
                            ),
                            as_="h4",
                            style=styles.h4_style,
                        ),
                        rx.text(
                            constants.SERVICE_4_DESCRIPTION,
                            style=[
                                styles.parragraph_text_style,
                                styles.service_parragraph_style,
                            ],
                        ),
                        style=styles.services_icon_box_style,
                    ),
                    style=[
                        styles.services_col_style,
                        styles.d_flex_style,
                        styles.align_items_stretch_style,
                        styles.mt_4_style,
                        styles.mt_xl_0_style,
                    ],
                ),
                style=styles.row_style,
            ),
            style=styles.container_style,
        ),
        style=styles.section_style,
    )
